# Generated by Django 4.2.4 on 2023-08-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('types', models.CharField(max_length=32)),
                ('vendor', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('in_stock', models.BooleanField(default=True)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('manual', models.FileField(upload_to='')),
            ],
        ),
    ]
