# Generated by Django 4.2.4 on 2023-08-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='manufacture_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manual',
        ),
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='manual_path',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('CARD', 'Prox Access Cards'), ('DECAL', 'Barcode Decal Sticker'), ('FOB', 'Prox Key Fob'), ('REMOTE', 'Prox Button Transmitter'), ('TAG', 'Prox RFID/UHF Tag')], max_length=32),
        ),
    ]
