# Generated by Django 4.2.4 on 2023-08-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_vendor_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('Prox Access Cards', 'CARD'), ('Barcode Decal Sticker', 'DECAL'), ('Prox Key Fob', 'FOB'), ('Prox Button Transmitter', 'REMOTE'), ('Prox RFID/UHF Tag', 'TAG')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('', 'AL'), ('', 'AK'), ('', 'AZ'), ('', 'AR'), ('', 'AS'), ('', 'CA'), ('', 'CO'), ('', 'CT'), ('', 'DE'), ('', 'DC'), ('', 'FL'), ('', 'GA'), ('', 'GU'), ('', 'HI'), ('', 'ID'), ('', 'IL'), ('', 'IN'), ('', 'IA'), ('', 'KS'), ('', 'KY'), ('', 'LA'), ('', 'ME'), ('', 'MD'), ('', 'MA'), ('', 'MI'), ('', 'MN'), ('', 'MS'), ('', 'MO'), ('', 'MT'), ('', 'NE'), ('', 'NV'), ('', 'NH'), ('', 'NJ'), ('', 'NM'), ('', 'NY'), ('', 'NC'), ('', 'ND'), ('', 'MP'), ('', 'OH'), ('', 'OK'), ('', 'OR'), ('', 'PA'), ('', 'PR'), ('', 'RI'), ('', 'SC'), ('', 'SD'), ('', 'TN'), ('', 'TX'), ('', 'TT'), ('', 'UT'), ('', 'VT'), ('', 'VA'), ('', 'VI'), ('', 'WA'), ('', 'WV'), ('', 'WI'), ('', 'WY')], max_length=2),
        ),
    ]
